services:
  - type: web
    name: simulador-leads-prestes
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --chdir leads_model app_dash:server
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
